### ISSUE TITLE
No native classes names in identifiers names

### ISSUE THREAD

**Issue by constgen** [atomspace/eslint-plugin-naming-convention#28]
Forbid class names in variables. eg `varNameArray`, `varNameObject`. Variables should be named `varNames` if it is a collection of items.

**Comment by PyTechMike** [comment]
Is this rule forbids using the name of a different class in another, e.g. `let someObject = 1` or `let anyArray = function() {}` ?

**Comment by constgen** [comment]
No. It disallows using this redundant words for any type of value

**Comment by constgen** [comment]
Something similar from TypeScript world https://palantir.github.io/tslint/rules/variable-name/

![image](https://user-images.githubusercontent.com/673144/68025527-ae982f00-fcb5-11e9-9ca6-b5738cbac25b.png)

**Comment by PyTechMike** [comment]
How hard is it prohibiting native class names? For example, we got `Map` and 
`Set` prohibited, but will be `` and `` prohibited too?

**Comment by PyTechMike** [comment]
Here is my forbidden classes list:
```
NaN
undefined
null
Object
Function
Boolean
Symbol
Error
Number
Date
String
RegExp
Array
Map
Set
Promise
Generator

```
Here is [source ](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects)

**Comment by PyTechMike** [comment]
What would you say about my last comment with prohibited classes in identifiers? Is it looking ok, or I'm going the wrong way?

**Comment by constgen** [comment]
WE definitely need to exclude `Error`, `Date`, `RegExp`
